export const SPARVG_SOURCE = {
  slug: 'sparvg',
  name: 'Santa Biblia Reina Valera Gómez',
  language: 'es',
  license: 'Copyright © 2004, 2010, 2023 Dr. Humberto Gómez Caballero. Distribución gratuita permitida sin alteración del texto.',
  source: 'eBible.org - https://ebible.org/find/details.php?id=sparvg',
  usfmZipUrl: 'https://eBible.org/Scriptures/sparvg_usfm.zip',
} as const;

export type SparvgBook = {
  id: string;
  testament: 'AT' | 'NT';
  name: string;
  slug: string;
  abbreviation: string;
  order: number;
};

export const SPARVG_BOOKS: SparvgBook[] = [
  { id: 'GEN', testament: 'AT', name: 'Génesis', slug: 'genesis', abbreviation: 'Gn', order: 1 },
  { id: 'EXO', testament: 'AT', name: 'Éxodo', slug: 'exodo', abbreviation: 'Ex', order: 2 },
  { id: 'LEV', testament: 'AT', name: 'Levítico', slug: 'levitico', abbreviation: 'Lv', order: 3 },
  { id: 'NUM', testament: 'AT', name: 'Números', slug: 'numeros', abbreviation: 'Nm', order: 4 },
  { id: 'DEU', testament: 'AT', name: 'Deuteronomio', slug: 'deuteronomio', abbreviation: 'Dt', order: 5 },
  { id: 'JOS', testament: 'AT', name: 'Josué', slug: 'josue', abbreviation: 'Jos', order: 6 },
  { id: 'JDG', testament: 'AT', name: 'Jueces', slug: 'jueces', abbreviation: 'Jue', order: 7 },
  { id: 'RUT', testament: 'AT', name: 'Rut', slug: 'rut', abbreviation: 'Rt', order: 8 },
  { id: '1SA', testament: 'AT', name: '1 Samuel', slug: '1-samuel', abbreviation: '1 S', order: 9 },
  { id: '2SA', testament: 'AT', name: '2 Samuel', slug: '2-samuel', abbreviation: '2 S', order: 10 },
  { id: '1KI', testament: 'AT', name: '1 Reyes', slug: '1-reyes', abbreviation: '1 R', order: 11 },
  { id: '2KI', testament: 'AT', name: '2 Reyes', slug: '2-reyes', abbreviation: '2 R', order: 12 },
  { id: '1CH', testament: 'AT', name: '1 Crónicas', slug: '1-cronicas', abbreviation: '1 Cr', order: 13 },
  { id: '2CH', testament: 'AT', name: '2 Crónicas', slug: '2-cronicas', abbreviation: '2 Cr', order: 14 },
  { id: 'EZR', testament: 'AT', name: 'Esdras', slug: 'esdras', abbreviation: 'Esd', order: 15 },
  { id: 'NEH', testament: 'AT', name: 'Nehemías', slug: 'nehemias', abbreviation: 'Neh', order: 16 },
  { id: 'EST', testament: 'AT', name: 'Ester', slug: 'ester', abbreviation: 'Est', order: 17 },
  { id: 'JOB', testament: 'AT', name: 'Job', slug: 'job', abbreviation: 'Job', order: 18 },
  { id: 'PSA', testament: 'AT', name: 'Salmos', slug: 'salmos', abbreviation: 'Sal', order: 19 },
  { id: 'PRO', testament: 'AT', name: 'Proverbios', slug: 'proverbios', abbreviation: 'Pr', order: 20 },
  { id: 'ECC', testament: 'AT', name: 'Eclesiastés', slug: 'eclesiastes', abbreviation: 'Ec', order: 21 },
  { id: 'SNG', testament: 'AT', name: 'Cantar de los Cantares', slug: 'cantar-de-los-cantares', abbreviation: 'Cnt', order: 22 },
  { id: 'ISA', testament: 'AT', name: 'Isaías', slug: 'isaias', abbreviation: 'Is', order: 23 },
  { id: 'JER', testament: 'AT', name: 'Jeremías', slug: 'jeremias', abbreviation: 'Jer', order: 24 },
  { id: 'LAM', testament: 'AT', name: 'Lamentaciones', slug: 'lamentaciones', abbreviation: 'Lm', order: 25 },
  { id: 'EZK', testament: 'AT', name: 'Ezequiel', slug: 'ezequiel', abbreviation: 'Ez', order: 26 },
  { id: 'DAN', testament: 'AT', name: 'Daniel', slug: 'daniel', abbreviation: 'Dn', order: 27 },
  { id: 'HOS', testament: 'AT', name: 'Oseas', slug: 'oseas', abbreviation: 'Os', order: 28 },
  { id: 'JOL', testament: 'AT', name: 'Joel', slug: 'joel', abbreviation: 'Jl', order: 29 },
  { id: 'AMO', testament: 'AT', name: 'Amós', slug: 'amos', abbreviation: 'Am', order: 30 },
  { id: 'OBA', testament: 'AT', name: 'Abdías', slug: 'abdias', abbreviation: 'Abd', order: 31 },
  { id: 'JON', testament: 'AT', name: 'Jonás', slug: 'jonas', abbreviation: 'Jon', order: 32 },
  { id: 'MIC', testament: 'AT', name: 'Miqueas', slug: 'miqueas', abbreviation: 'Mi', order: 33 },
  { id: 'NAM', testament: 'AT', name: 'Nahúm', slug: 'nahum', abbreviation: 'Nah', order: 34 },
  { id: 'HAB', testament: 'AT', name: 'Habacuc', slug: 'habacuc', abbreviation: 'Hab', order: 35 },
  { id: 'ZEP', testament: 'AT', name: 'Sofonías', slug: 'sofonias', abbreviation: 'Sof', order: 36 },
  { id: 'HAG', testament: 'AT', name: 'Hageo', slug: 'hageo', abbreviation: 'Hag', order: 37 },
  { id: 'ZEC', testament: 'AT', name: 'Zacarías', slug: 'zacarias', abbreviation: 'Zac', order: 38 },
  { id: 'MAL', testament: 'AT', name: 'Malaquías', slug: 'malaquias', abbreviation: 'Mal', order: 39 },
  { id: 'MAT', testament: 'NT', name: 'Mateo', slug: 'mateo', abbreviation: 'Mt', order: 40 },
  { id: 'MRK', testament: 'NT', name: 'Marcos', slug: 'marcos', abbreviation: 'Mr', order: 41 },
  { id: 'LUK', testament: 'NT', name: 'Lucas', slug: 'lucas', abbreviation: 'Lc', order: 42 },
  { id: 'JHN', testament: 'NT', name: 'Juan', slug: 'juan', abbreviation: 'Jn', order: 43 },
  { id: 'ACT', testament: 'NT', name: 'Hechos', slug: 'hechos', abbreviation: 'Hch', order: 44 },
  { id: 'ROM', testament: 'NT', name: 'Romanos', slug: 'romanos', abbreviation: 'Ro', order: 45 },
  { id: '1CO', testament: 'NT', name: '1 Corintios', slug: '1-corintios', abbreviation: '1 Co', order: 46 },
  { id: '2CO', testament: 'NT', name: '2 Corintios', slug: '2-corintios', abbreviation: '2 Co', order: 47 },
  { id: 'GAL', testament: 'NT', name: 'Gálatas', slug: 'galatas', abbreviation: 'Ga', order: 48 },
  { id: 'EPH', testament: 'NT', name: 'Efesios', slug: 'efesios', abbreviation: 'Ef', order: 49 },
  { id: 'PHP', testament: 'NT', name: 'Filipenses', slug: 'filipenses', abbreviation: 'Fil', order: 50 },
  { id: 'COL', testament: 'NT', name: 'Colosenses', slug: 'colosenses', abbreviation: 'Col', order: 51 },
  { id: '1TH', testament: 'NT', name: '1 Tesalonicenses', slug: '1-tesalonicenses', abbreviation: '1 Ts', order: 52 },
  { id: '2TH', testament: 'NT', name: '2 Tesalonicenses', slug: '2-tesalonicenses', abbreviation: '2 Ts', order: 53 },
  { id: '1TI', testament: 'NT', name: '1 Timoteo', slug: '1-timoteo', abbreviation: '1 Ti', order: 54 },
  { id: '2TI', testament: 'NT', name: '2 Timoteo', slug: '2-timoteo', abbreviation: '2 Ti', order: 55 },
  { id: 'TIT', testament: 'NT', name: 'Tito', slug: 'tito', abbreviation: 'Tit', order: 56 },
  { id: 'PHM', testament: 'NT', name: 'Filemón', slug: 'filemon', abbreviation: 'Flm', order: 57 },
  { id: 'HEB', testament: 'NT', name: 'Hebreos', slug: 'hebreos', abbreviation: 'Heb', order: 58 },
  { id: 'JAS', testament: 'NT', name: 'Santiago', slug: 'santiago', abbreviation: 'Stg', order: 59 },
  { id: '1PE', testament: 'NT', name: '1 Pedro', slug: '1-pedro', abbreviation: '1 P', order: 60 },
  { id: '2PE', testament: 'NT', name: '2 Pedro', slug: '2-pedro', abbreviation: '2 P', order: 61 },
  { id: '1JN', testament: 'NT', name: '1 Juan', slug: '1-juan', abbreviation: '1 Jn', order: 62 },
  { id: '2JN', testament: 'NT', name: '2 Juan', slug: '2-juan', abbreviation: '2 Jn', order: 63 },
  { id: '3JN', testament: 'NT', name: '3 Juan', slug: '3-juan', abbreviation: '3 Jn', order: 64 },
  { id: 'JUD', testament: 'NT', name: 'Judas', slug: 'judas', abbreviation: 'Jud', order: 65 },
  { id: 'REV', testament: 'NT', name: 'Apocalipsis', slug: 'apocalipsis', abbreviation: 'Ap', order: 66 },
];
