import { db } from './client';
import { planLectura, libros } from './schema';

type DayReading = {
  slug: string;
  capituloInicio: number;
  capituloFin: number | null;
};

type PlanMonth = DayReading[][];

const PLAN: Record<number, PlanMonth> = {
  1: [ // ENERO
    [{ slug: 'juan', capituloInicio: 1, capituloFin: null }],
    [{ slug: 'genesis', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'genesis', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'genesis', capituloInicio: 9, capituloFin: 12 }],
    [{ slug: 'salmos', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'genesis', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'genesis', capituloInicio: 17, capituloFin: 19 }],
    [{ slug: 'genesis', capituloInicio: 20, capituloFin: 22 }],
    [{ slug: 'job', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'job', capituloInicio: 4, capituloFin: 7 }],
    [{ slug: 'job', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: 'salmos', capituloInicio: 4, capituloFin: 7 }],
    [{ slug: 'job', capituloInicio: 12, capituloFin: 14 }],
    [{ slug: 'job', capituloInicio: 15, capituloFin: 17 }],
    [{ slug: 'job', capituloInicio: 18, capituloFin: 21 }],
    [{ slug: 'job', capituloInicio: 22, capituloFin: 25 }],
    [{ slug: 'job', capituloInicio: 26, capituloFin: 31 }],
    [{ slug: 'job', capituloInicio: 32, capituloFin: 34 }],
    [{ slug: 'salmos', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: 'job', capituloInicio: 35, capituloFin: 37 }],
    [{ slug: 'job', capituloInicio: 38, capituloFin: 42 }],
    [{ slug: 'genesis', capituloInicio: 23, capituloFin: 26 }],
    [{ slug: 'genesis', capituloInicio: 27, capituloFin: 30 }],
    [{ slug: 'genesis', capituloInicio: 31, capituloFin: 34 }],
    [{ slug: 'genesis', capituloInicio: 35, capituloFin: 38 }],
    [{ slug: 'salmos', capituloInicio: 12, capituloFin: 14 }],
    [{ slug: 'genesis', capituloInicio: 39, capituloFin: 42 }],
    [{ slug: 'genesis', capituloInicio: 43, capituloFin: 46 }],
    [{ slug: 'genesis', capituloInicio: 47, capituloFin: 50 }],
    [{ slug: 'exodo', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'exodo', capituloInicio: 4, capituloFin: 6 }],
  ],
  2: [ // FEBRERO
    [{ slug: 'exodo', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'salmos', capituloInicio: 15, capituloFin: 17 }],
    [{ slug: 'exodo', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'exodo', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'exodo', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'exodo', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'exodo', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'exodo', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'salmos', capituloInicio: 18, capituloFin: 20 }],
    [{ slug: 'exodo', capituloInicio: 28, capituloFin: 30 }],
    [{ slug: 'exodo', capituloInicio: 31, capituloFin: 33 }],
    [{ slug: 'exodo', capituloInicio: 34, capituloFin: 37 }],
    [{ slug: 'exodo', capituloInicio: 38, capituloFin: 40 }],
    [{ slug: 'levitico', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'levitico', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'salmos', capituloInicio: 21, capituloFin: 23 }],
    [{ slug: 'levitico', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'levitico', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'levitico', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'levitico', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'levitico', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'levitico', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'salmos', capituloInicio: 24, capituloFin: 26 }],
    [{ slug: 'levitico', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'numeros', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'numeros', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'numeros', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'numeros', capituloInicio: 10, capituloFin: 12 }],
  ],
  3: [ // MARZO
    [{ slug: 'numeros', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'salmos', capituloInicio: 27, capituloFin: 29 }],
    [{ slug: 'numeros', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'numeros', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'numeros', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'numeros', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'numeros', capituloInicio: 28, capituloFin: 30 }],
    [{ slug: 'numeros', capituloInicio: 31, capituloFin: 33 }],
    [{ slug: 'salmos', capituloInicio: 30, capituloFin: 32 }],
    [{ slug: 'numeros', capituloInicio: 34, capituloFin: 36 }],
    [{ slug: 'deuteronomio', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'deuteronomio', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'deuteronomio', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'deuteronomio', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'deuteronomio', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'salmos', capituloInicio: 33, capituloFin: 35 }],
    [{ slug: 'deuteronomio', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'deuteronomio', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'deuteronomio', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'deuteronomio', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'deuteronomio', capituloInicio: 28, capituloFin: 30 }],
    [{ slug: 'deuteronomio', capituloInicio: 31, capituloFin: 34 }],
    [{ slug: 'salmos', capituloInicio: 36, capituloFin: 38 }],
    [{ slug: 'josue', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'josue', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'josue', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'josue', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'josue', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'josue', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'salmos', capituloInicio: 39, capituloFin: 41 }],
    [{ slug: 'josue', capituloInicio: 19, capituloFin: 21 }],
  ],
  4: [ // ABRIL
    [{ slug: 'josue', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'jueces', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'jueces', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'jueces', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'jueces', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'salmos', capituloInicio: 42, capituloFin: 44 }],
    [{ slug: 'jueces', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'jueces', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'jueces', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'rut', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: '1-samuel', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: '1-samuel', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'salmos', capituloInicio: 45, capituloFin: 47 }],
    [{ slug: '1-samuel', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: '1-samuel', capituloInicio: 10, capituloFin: 13 }],
    [{ slug: '1-samuel', capituloInicio: 14, capituloFin: 16 }],
    [{ slug: '1-samuel', capituloInicio: 17, capituloFin: 19 }],
    [{ slug: '1-samuel', capituloInicio: 20, capituloFin: 22 }],
    [{ slug: '1-samuel', capituloInicio: 23, capituloFin: 25 }],
    [{ slug: 'salmos', capituloInicio: 48, capituloFin: 50 }],
    [{ slug: '1-samuel', capituloInicio: 26, capituloFin: 28 }],
    [{ slug: '1-samuel', capituloInicio: 29, capituloFin: 31 }],
    [{ slug: '2-samuel', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: '2-samuel', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: '2-samuel', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: '2-samuel', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'salmos', capituloInicio: 51, capituloFin: 53 }],
    [{ slug: '2-samuel', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: '2-samuel', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: '2-samuel', capituloInicio: 19, capituloFin: 21 }],
  ],
  5: [ // MAYO
    [{ slug: '2-samuel', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: '1-reyes', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'proverbios', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'salmos', capituloInicio: 54, capituloFin: 56 }],
    [{ slug: 'proverbios', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'proverbios', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'proverbios', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'proverbios', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'proverbios', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'proverbios', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'salmos', capituloInicio: 57, capituloFin: 59 }],
    [{ slug: 'proverbios', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'proverbios', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'proverbios', capituloInicio: 28, capituloFin: 31 }],
    [{ slug: 'cantar-de-los-cantares', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'cantar-de-los-cantares', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: '1-reyes', capituloInicio: 5, capituloFin: 7 }],
    [{ slug: 'salmos', capituloInicio: 60, capituloFin: 62 }],
    [{ slug: '1-reyes', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: 'eclesiastes', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'eclesiastes', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'eclesiastes', capituloInicio: 9, capituloFin: 12 }],
    [{ slug: '1-reyes', capituloInicio: 12, capituloFin: 14 }],
    [{ slug: '1-reyes', capituloInicio: 15, capituloFin: 17 }],
    [{ slug: 'salmos', capituloInicio: 63, capituloFin: 65 }],
    [{ slug: '1-reyes', capituloInicio: 18, capituloFin: 20 }],
    [
      { slug: '1-reyes', capituloInicio: 21, capituloFin: 22 },
      { slug: '2-reyes', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: '2-reyes', capituloInicio: 2, capituloFin: 4 }],
    [{ slug: '2-reyes', capituloInicio: 5, capituloFin: 7 }],
    [{ slug: '2-reyes', capituloInicio: 8, capituloFin: 10 }],
    [{ slug: '2-reyes', capituloInicio: 11, capituloFin: 14 }],
  ],
  6: [ // JUNIO
    [{ slug: 'salmos', capituloInicio: 66, capituloFin: 68 }],
    [{ slug: 'jonas', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'amos', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'amos', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'amos', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: '2-reyes', capituloInicio: 15, capituloFin: 17 }],
    [{ slug: '2-reyes', capituloInicio: 18, capituloFin: 21 }],
    [{ slug: 'salmos', capituloInicio: 69, capituloFin: 71 }],
    [{ slug: '2-reyes', capituloInicio: 22, capituloFin: 25 }],
    [{ slug: '1-cronicas', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: '1-cronicas', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: '1-cronicas', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: '1-cronicas', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: '1-cronicas', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'salmos', capituloInicio: 72, capituloFin: 74 }],
    [{ slug: '1-cronicas', capituloInicio: 17, capituloFin: 19 }],
    [{ slug: '1-cronicas', capituloInicio: 20, capituloFin: 22 }],
    [{ slug: '1-cronicas', capituloInicio: 23, capituloFin: 25 }],
    [{ slug: '1-cronicas', capituloInicio: 26, capituloFin: 29 }],
    [{ slug: '2-cronicas', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: '2-cronicas', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'salmos', capituloInicio: 75, capituloFin: 77 }],
    [{ slug: '2-cronicas', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: '2-cronicas', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: '2-cronicas', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: '2-cronicas', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: '2-cronicas', capituloInicio: 19, capituloFin: 22 }],
    [
      { slug: 'joel', capituloInicio: 1, capituloFin: 3 },
      { slug: 'abdias', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: 'salmos', capituloInicio: 78, capituloFin: 80 }],
    [{ slug: '2-cronicas', capituloInicio: 23, capituloFin: 26 }],
  ],
  7: [ // JULIO
    [{ slug: 'isaias', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'isaias', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: '2-cronicas', capituloInicio: 27, capituloFin: 29 }],
    [{ slug: '2-cronicas', capituloInicio: 30, capituloFin: 32 }],
    [{ slug: 'isaias', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'salmos', capituloInicio: 81, capituloFin: 83 }],
    [{ slug: 'isaias', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'isaias', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'isaias', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'isaias', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'isaias', capituloInicio: 22, capituloFin: 24 }],
    [{ slug: 'isaias', capituloInicio: 25, capituloFin: 27 }],
    [{ slug: 'salmos', capituloInicio: 84, capituloFin: 86 }],
    [{ slug: 'isaias', capituloInicio: 28, capituloFin: 30 }],
    [{ slug: 'isaias', capituloInicio: 31, capituloFin: 33 }],
    [{ slug: 'isaias', capituloInicio: 34, capituloFin: 36 }],
    [{ slug: 'isaias', capituloInicio: 37, capituloFin: 39 }],
    [{ slug: 'isaias', capituloInicio: 40, capituloFin: 42 }],
    [{ slug: 'isaias', capituloInicio: 43, capituloFin: 45 }],
    [{ slug: 'salmos', capituloInicio: 87, capituloFin: 90 }],
    [{ slug: 'isaias', capituloInicio: 46, capituloFin: 48 }],
    [{ slug: 'isaias', capituloInicio: 49, capituloFin: 51 }],
    [{ slug: 'isaias', capituloInicio: 52, capituloFin: 54 }],
    [{ slug: 'isaias', capituloInicio: 55, capituloFin: 57 }],
    [{ slug: 'isaias', capituloInicio: 58, capituloFin: 60 }],
    [{ slug: 'isaias', capituloInicio: 61, capituloFin: 63 }],
    [{ slug: 'salmos', capituloInicio: 91, capituloFin: 93 }],
    [{ slug: 'isaias', capituloInicio: 64, capituloFin: 66 }],
    [{ slug: 'oseas', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'oseas', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'oseas', capituloInicio: 7, capituloFin: 9 }],
  ],
  8: [ // AGOSTO
    [{ slug: 'oseas', capituloInicio: 10, capituloFin: 12 }],
    [
      { slug: 'oseas', capituloInicio: 13, capituloFin: 14 },
      { slug: 'miqueas', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: 'salmos', capituloInicio: 94, capituloFin: 96 }],
    [{ slug: 'miqueas', capituloInicio: 2, capituloFin: 4 }],
    [{ slug: 'miqueas', capituloInicio: 5, capituloFin: 7 }],
    [{ slug: 'nahum', capituloInicio: 1, capituloFin: 3 }],
    [
      { slug: '2-cronicas', capituloInicio: 33, capituloFin: 34 },
      { slug: 'sofonias', capituloInicio: 1, capituloFin: null },
    ],
    [
      { slug: 'sofonias', capituloInicio: 2, capituloFin: 3 },
      { slug: '2-cronicas', capituloInicio: 35, capituloFin: null },
    ],
    [{ slug: 'habacuc', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'salmos', capituloInicio: 97, capituloFin: 99 }],
    [{ slug: 'jeremias', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'jeremias', capituloInicio: 4, capituloFin: 6 }],
    [
      { slug: 'jeremias', capituloInicio: 11, capituloFin: 12 },
      { slug: 'jeremias', capituloInicio: 26, capituloFin: null },
    ],
    [{ slug: 'jeremias', capituloInicio: 7, capituloFin: 9 }],
    [
      { slug: 'jeremias', capituloInicio: 10, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 14, capituloFin: 15 },
    ],
    [{ slug: 'jeremias', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'salmos', capituloInicio: 100, capituloFin: 102 }],
    [
      { slug: 'jeremias', capituloInicio: 19, capituloFin: 20 },
      { slug: 'jeremias', capituloInicio: 35, capituloFin: null },
    ],
    [
      { slug: 'jeremias', capituloInicio: 25, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 36, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 45, capituloFin: null },
    ],
    [{ slug: 'jeremias', capituloInicio: 46, capituloFin: 49 }],
    [
      { slug: 'jeremias', capituloInicio: 13, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 22, capituloFin: 23 },
    ],
    [
      { slug: 'jeremias', capituloInicio: 24, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 27, capituloFin: 28 },
    ],
    [
      { slug: 'jeremias', capituloInicio: 29, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 50, capituloFin: 51 },
    ],
    [{ slug: 'salmos', capituloInicio: 103, capituloFin: 105 }],
    [{ slug: 'jeremias', capituloInicio: 30, capituloFin: 33 }],
    [
      { slug: 'jeremias', capituloInicio: 21, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 34, capituloFin: null },
      { slug: 'jeremias', capituloInicio: 37, capituloFin: null },
    ],
    [
      { slug: 'jeremias', capituloInicio: 38, capituloFin: 39 },
      { slug: 'jeremias', capituloInicio: 52, capituloFin: null },
    ],
    [{ slug: 'jeremias', capituloInicio: 40, capituloFin: 42 }],
    [
      { slug: 'jeremias', capituloInicio: 43, capituloFin: 44 },
      { slug: 'lamentaciones', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: 'lamentaciones', capituloInicio: 2, capituloFin: 5 }],
    [{ slug: 'salmos', capituloInicio: 106, capituloFin: 108 }],
  ],
  9: [ // SEPTIEMBRE
    [
      { slug: '2-cronicas', capituloInicio: 36, capituloFin: null },
      { slug: 'daniel', capituloInicio: 1, capituloFin: 3 },
    ],
    [{ slug: 'daniel', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'daniel', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'daniel', capituloInicio: 10, capituloFin: 12 }],
    [
      { slug: '2-cronicas', capituloInicio: 36, capituloFin: null },
      { slug: 'ezequiel', capituloInicio: 1, capituloFin: 3 },
    ],
    [{ slug: 'ezequiel', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'salmos', capituloInicio: 109, capituloFin: 111 }],
    [{ slug: 'ezequiel', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'ezequiel', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'ezequiel', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'ezequiel', capituloInicio: 17, capituloFin: 20 }],
    [{ slug: 'ezequiel', capituloInicio: 21, capituloFin: 24 }],
    [{ slug: 'ezequiel', capituloInicio: 25, capituloFin: 28 }],
    [{ slug: 'salmos', capituloInicio: 112, capituloFin: 114 }],
    [{ slug: 'ezequiel', capituloInicio: 29, capituloFin: 32 }],
    [{ slug: 'ezequiel', capituloInicio: 33, capituloFin: 36 }],
    [{ slug: 'ezequiel', capituloInicio: 37, capituloFin: 40 }],
    [{ slug: 'ezequiel', capituloInicio: 41, capituloFin: 44 }],
    [{ slug: 'ezequiel', capituloInicio: 45, capituloFin: 48 }],
    [
      { slug: '2-cronicas', capituloInicio: 36, capituloFin: null },
      { slug: 'esdras', capituloInicio: 1, capituloFin: 3 },
    ],
    [{ slug: 'salmos', capituloInicio: 115, capituloFin: 117 }],
    [
      { slug: 'esdras', capituloInicio: 4, capituloFin: null },
      { slug: 'hageo', capituloInicio: 1, capituloFin: 2 },
    ],
    [{ slug: 'zacarias', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'zacarias', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'zacarias', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'zacarias', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'zacarias', capituloInicio: 13, capituloFin: 14 }],
    [{ slug: 'salmos', capituloInicio: 118, capituloFin: 119 }],
    [{ slug: 'esdras', capituloInicio: 5, capituloFin: 7 }],
    [{ slug: 'esdras', capituloInicio: 8, capituloFin: 10 }],
  ],
  10: [ // OCTUBRE
    [{ slug: 'ester', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'ester', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'ester', capituloInicio: 7, capituloFin: 10 }],
    [{ slug: 'nehemias', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'salmos', capituloInicio: 119, capituloFin: null }],
    [{ slug: 'nehemias', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'nehemias', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'nehemias', capituloInicio: 10, capituloFin: 13 }],
    [{ slug: 'malaquias', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'mateo', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'mateo', capituloInicio: 4, capituloFin: 7 }],
    [{ slug: 'salmos', capituloInicio: 119, capituloFin: null }],
    [{ slug: 'mateo', capituloInicio: 8, capituloFin: 10 }],
    [{ slug: 'mateo', capituloInicio: 11, capituloFin: 13 }],
    [{ slug: 'mateo', capituloInicio: 14, capituloFin: 16 }],
    [{ slug: 'mateo', capituloInicio: 17, capituloFin: 19 }],
    [{ slug: 'mateo', capituloInicio: 20, capituloFin: 22 }],
    [{ slug: 'mateo', capituloInicio: 23, capituloFin: 25 }],
    [{ slug: 'salmos', capituloInicio: 119, capituloFin: null }],
    [{ slug: 'mateo', capituloInicio: 26, capituloFin: 28 }],
    [{ slug: 'marcos', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'marcos', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'marcos', capituloInicio: 9, capituloFin: 12 }],
    [{ slug: 'marcos', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'lucas', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'salmos', capituloInicio: 120, capituloFin: 122 }],
    [{ slug: 'lucas', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'lucas', capituloInicio: 9, capituloFin: 12 }],
    [{ slug: 'lucas', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'lucas', capituloInicio: 17, capituloFin: 20 }],
    [{ slug: 'lucas', capituloInicio: 21, capituloFin: 24 }],
  ],
  11: [ // NOVIEMBRE
    [{ slug: 'juan', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'salmos', capituloInicio: 123, capituloFin: 125 }],
    [{ slug: 'juan', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'juan', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'juan', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'juan', capituloInicio: 13, capituloFin: 15 }],
    [{ slug: 'juan', capituloInicio: 16, capituloFin: 18 }],
    [{ slug: 'juan', capituloInicio: 19, capituloFin: 21 }],
    [{ slug: 'salmos', capituloInicio: 126, capituloFin: 128 }],
    [{ slug: 'hechos', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'hechos', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'hechos', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: 'hechos', capituloInicio: 12, capituloFin: 14 }],
    [{ slug: 'santiago', capituloInicio: 1, capituloFin: 5 }],
    [{ slug: 'galatas', capituloInicio: 1, capituloFin: 6 }],
    [{ slug: 'salmos', capituloInicio: 129, capituloFin: 131 }],
    [{ slug: 'hechos', capituloInicio: 15, capituloFin: 16 }],
    [{ slug: 'filipenses', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: '1-tesalonicenses', capituloInicio: 1, capituloFin: 5 }],
    [
      { slug: 'hechos', capituloInicio: 17, capituloFin: 18 },
      { slug: '2-tesalonicenses', capituloInicio: 1, capituloFin: 3 },
    ],
    [{ slug: '1-corintios', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: '1-corintios', capituloInicio: 4, capituloFin: 7 }],
    [{ slug: 'salmos', capituloInicio: 132, capituloFin: 134 }],
    [{ slug: '1-corintios', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: '1-corintios', capituloInicio: 11, capituloFin: 14 }],
    [{ slug: '1-corintios', capituloInicio: 15, capituloFin: 16 }],
    [{ slug: '2-corintios', capituloInicio: 1, capituloFin: 5 }],
    [{ slug: '2-corintios', capituloInicio: 6, capituloFin: 9 }],
    [{ slug: '2-corintios', capituloInicio: 10, capituloFin: 13 }],
    [{ slug: 'salmos', capituloInicio: 135, capituloFin: 137 }],
  ],
  12: [ // DICIEMBRE
    [
      { slug: 'hechos', capituloInicio: 18, capituloFin: 19 },
      { slug: 'efesios', capituloInicio: 1, capituloFin: 2 },
    ],
    [{ slug: 'efesios', capituloInicio: 3, capituloFin: 6 }],
    [{ slug: 'romanos', capituloInicio: 1, capituloFin: 3 }],
    [{ slug: 'romanos', capituloInicio: 4, capituloFin: 6 }],
    [{ slug: 'romanos', capituloInicio: 7, capituloFin: 9 }],
    [{ slug: 'romanos', capituloInicio: 10, capituloFin: 12 }],
    [{ slug: 'salmos', capituloInicio: 138, capituloFin: 140 }],
    [{ slug: 'romanos', capituloInicio: 13, capituloFin: 16 }],
    [{ slug: 'hechos', capituloInicio: 20, capituloFin: 22 }],
    [{ slug: 'hechos', capituloInicio: 23, capituloFin: 25 }],
    [{ slug: 'hechos', capituloInicio: 26, capituloFin: 28 }],
    [{ slug: 'colosenses', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'hebreos', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'salmos', capituloInicio: 141, capituloFin: 143 }],
    [{ slug: 'hebreos', capituloInicio: 5, capituloFin: 8 }],
    [{ slug: 'hebreos', capituloInicio: 9, capituloFin: 11 }],
    [
      { slug: 'hebreos', capituloInicio: 12, capituloFin: 13 },
      { slug: 'tito', capituloInicio: 1, capituloFin: 3 },
    ],
    [{ slug: '1-timoteo', capituloInicio: 1, capituloFin: 6 }],
    [
      { slug: '2-timoteo', capituloInicio: 1, capituloFin: 4 },
      { slug: 'filemon', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: '1-pedro', capituloInicio: 1, capituloFin: 5 }],
    [{ slug: 'salmos', capituloInicio: 144, capituloFin: 146 }],
    [{ slug: '1-juan', capituloInicio: 1, capituloFin: 5 }],
    [
      { slug: '2-pedro', capituloInicio: 1, capituloFin: 3 },
      { slug: '2-juan', capituloInicio: 1, capituloFin: null },
      { slug: '3-juan', capituloInicio: 1, capituloFin: null },
      { slug: 'judas', capituloInicio: 1, capituloFin: null },
    ],
    [{ slug: 'apocalipsis', capituloInicio: 1, capituloFin: 4 }],
    [{ slug: 'apocalipsis', capituloInicio: 5, capituloFin: 7 }],
    [{ slug: 'apocalipsis', capituloInicio: 8, capituloFin: 11 }],
    [{ slug: 'apocalipsis', capituloInicio: 12, capituloFin: 13 }],
    [{ slug: 'salmos', capituloInicio: 147, capituloFin: 150 }],
    [{ slug: 'apocalipsis', capituloInicio: 14, capituloFin: 16 }],
    [{ slug: 'apocalipsis', capituloInicio: 17, capituloFin: 19 }],
    [{ slug: 'apocalipsis', capituloInicio: 20, capituloFin: 22 }],
  ],
};

export async function seedPlanLectura() {
  // Build libro slug → id map
  const allBooks = await db.select({ id: libros.id, slug: libros.slug }).from(libros);
  const slugToId = new Map(allBooks.map((b) => [b.slug, b.id]));

  // Clear existing plan
  await db.delete(planLectura);

  const rows: (typeof planLectura.$inferInsert)[] = [];

  for (const [mes, days] of Object.entries(PLAN)) {
    const mesNum = Number(mes);
    for (let dia = 0; dia < days.length; dia++) {
      const dayReadings = days[dia];
      for (let orden = 0; orden < dayReadings.length; orden++) {
        const r = dayReadings[orden];
        const libroId = slugToId.get(r.slug);
        if (!libroId) {
          console.warn(`Book slug "${r.slug}" not found in DB — skipping day ${mesNum}/${dia + 1}`);
          continue;
        }
        rows.push({
          mes: mesNum,
          dia: dia + 1,
          orden: orden + 1,
          libroId,
          capituloInicio: r.capituloInicio,
          capituloFin: r.capituloFin,
        });
      }
    }
  }

  await db.insert(planLectura).values(rows);
  console.log(`Inserted ${rows.length} plan_lectura rows.`);
}
